### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by jakepoolefin** [d60/twikit#171] opened 2024-08-05 02:36 UTC
Installed twikit, trying to run example and get error...
import asyncio
from twikit import Client
USERNAME = 'example_user'
EMAIL = 'email@example.com'
PASSWORD = 'password0000'
# Initialize client
client = Client('en-US')
async def main():
    await client.login(
######################################################################
###$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Traceback (most recent call last):
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 18, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 12, in main
    await client.login(
  File "/home/jakepoolefin/.local/lib/python3.10/site-packages/twikit/client/client.py", line 330, in login
    if flow.task_id == 'DenyLoginSubtask':
  File "/home/jakepoolefin/.local/lib/python3.10/site-packages/twikit/utils.py", line 103, in task_id
    return self.response['subtasks'][0]['subtask_id']
IndexError: list index out of range
jakepoolefin@cloudshell:~$ /bin/python /home/jakepoolefin/twitter/python_testing/testing.py
jakepoolefin@cloudshell:~$ /bin/python /home/jakepoolefin/twitter/python_testing/testing.py
Traceback (most recent call last):
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 18, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 12, in main
    await client.login(
  File "/home/jakepoolefin/.local/lib/python3.10/site-packages/twikit/client/client.py", line 330, in login
    if flow.task_id == 'DenyLoginSubtask':
  File "/home/jakepoolefin/.local/lib/python3.10/site-packages/twikit/utils.py", line 103, in task_id
    return self.response['subtasks'][0]['subtask_id']
IndexError: list index out of range
jakepoolefin@cloudshell:~$ /bin/python /home/jakepoolefin/twitter/python_testing/testing.py
Traceback (most recent call last):
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 28, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 13, in main
    await client.login(
  File "/home/jakepoolefin/.local/lib/python3.10/site-packages/twikit/client/client.py", line 330, in login
    if flow.task_id == 'DenyLoginSubtask':
  File "/home/jakepoolefin/.local/lib/python3.10/site-packages/twikit/utils.py", line 103, in task_id
    return self.response['subtasks'][0]['subtask_id']
IndexError: list index out of range
jakepoolefin@cloudshell:~$ /bin/python /home/jakepoolefin/twitter/python_testing/testing.py
/home/jakepoolefin/twitter/python_testing/testing.py:10: RuntimeWarning: coroutine 'Client.login' was never awaited
  client.login(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
jakepoolefin@cloudshell:~$ /bin/python /home/jakepoolefin/twitter/python_testing/testing.py
/home/jakepoolefin/twitter/python_testing/testing.py:10: RuntimeWarning: coroutine 'Client.login' was never awaited
  client.login(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
jakepoolefin@cloudshell:~$ /bin/python /home/jakepoolefin/twitter/python_testing/testing.py
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 10
    await client.login(
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: 'await' outside function
jakepoolefin@cloudshell:~$ /bin/python /home/jakepoolefin/twitter/python_testing/testing.py
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 11
    await client.login(
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: 'await' outside function
jakepoolefin@cloudshell:~$ /bin/python /home/jakepoolefin/twitter/python_testing/testing.py
Traceback (most recent call last):
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 17, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 12, in main
    await client.login(
  File "/home/jakepoolefin/.local/lib/python3.10/site-packages/twikit/client/client.py", line 330, in login
    if flow.task_id == 'DenyLoginSubtask':
  File "/home/jakepoolefin/.local/lib/python3.10/site-packages/twikit/utils.py", line 103, in task_id
    return self.response['subtasks'][0]['subtask_id']
IndexError: list index out of range
jakepoolefin@cloudshell:~$ /bin/python /home/jakepoolefin/twitter/python_testing/testing.py
Traceback (most recent call last):
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 18, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jakepoolefin/twitter/python_testing/testing.py", line 12, in main
    await client.login(
  File "/home/jakepoolefin/.local/lib/python3.10/site-packages/twikit/client/client.py", line 330, in login
    if flow.task_id == 'DenyLoginSubtask':
  File "/home/jakepoolefin/.local/lib/python3.10/site-packages/twikit/utils.py", line 103, in task_id
    return self.response['subtasks'][0]['subtask_id']
IndexError: list index out of range
        auth_info_1=USERNAME ,
        auth_info_2=EMAIL,
        password=PASSWORD
    )

asyncio.run(main())

**Comment by Choo-lux** [comment] 2024-08-05 07:10
DenyLoginSubtask

twitter is blocking it

**Comment by sarartur** [comment] 2024-08-05 12:53
I have the same issue, this is a duplicate of https://github.com/d60/twikit/issues/169

`DenyLoginSubtask` workflow doesn't get hit.

its failing because of call to `flow.task_id`... [self.response['subtasks']](https://github.com/d60/twikit/blob/main/twikit/utils.py#L103) is empty. Not sure what the cause of that is, but either way it would be nice to have some sort of handling or helpful error message

**Comment by jaepil-choi** [comment] 2024-08-09 08:47
I'm having the same issue. Seems like Twitter is indeed blocking the request.

**Comment by juratjan123** [comment] 2024-08-12 06:13
Having the same issue. 

```
File "/opt/anaconda3/envs/scraper/lib/python3.10/site-packages/twikit/utils.py", line 103, in task_id
    return self.response['subtasks'][0]['subtask_id']
IndexError: list index out of range
```

Sooo hard to get Tweets now.

**Comment by d60** [comment] 2024-08-17 15:00
Duplicate of #169

**Closed** 2024-08-17 15:01 UTC
