### ISSUE TITLE
DenyLoginSubtask

### ISSUE THREAD

**Issue by umutbozdag** [d60/twikit#174] opened 2024-08-10 16:35 UTC
I got this error when trying to login: in task_id
    return self.response['subtasks'][0]['subtask_id']
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Is there any known fix to this?

**Comment by d60** [comment] 2024-08-17 15:00
Duplicate of #169

**Closed by d60** 2024-08-17 15:00 UTC
