### ISSUE TITLE
flow name LoginFlow is currently not accessible"}]}"

### ISSUE THREAD

**Issue by DemianOportus** [d60/twikit#198] opened 2024-09-01 01:57 UTC
I am using the most basic example and it isn't working. Any solutions?

`import asyncio

from twikit import Client

## Enter your account information
USERNAME = XXXX
EMAIL = XXXX
PASSWORD = XXXX

client = Client('en-US')

async def main():
    ## Asynchronous client methods are coroutines and
    ## must be called using `await`.
    await client.login(
        auth_info_1=USERNAME,
        auth_info_2=EMAIL,
        password=PASSWORD
    )

asyncio.run(main())`

Same error, 

statsgetter/main.py", line 23, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/chris/Desktop/statsgetter/main.py", line 17, in main
    await client.login(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/twikit/client/client.py", line 400, in login
    await flow.execute_task({
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/twikit/utils.py", line 88, in execute_task
    response, _ = await self._client.v11.onboarding_task(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/twikit/client/v11.py", line 85, in onboarding_task
    return await self.base.post(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/twikit/client/client.py", line 190, in post
    return await self.request('POST', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/twikit/client/client.py", line 164, in request
    raise BadRequest(message, headers=response.headers)
twikit.errors.BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

**Comment by ayanavasarkar** [comment] 2024-09-01 03:25
Getting the same error.

**Comment by DemianOportus** [comment] 2024-09-01 16:15
> Getting the same error.

[Here](https://github.com/d60/twikit/issues/196#issuecomment-2323123750) is my solution:

**Comment by d60** [comment] 2024-09-19 22:16
Duplicate of #169

**Closed by d60** 2024-09-19 22:16 UTC
