### ISSUE TITLE
twikit.errors.BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

### ISSUE THREAD

**Issue by Carsoncantcode** [d60/twikit#221] opened 2024-09-19 18:23 UTC
twikit.errors.BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

I get this error when trying to get my cookies

**Comment by d60** [comment] 2024-09-19 22:15
Duplicate of #169

**Closed by d60** 2024-09-19 22:15 UTC
